# 2D Costmap parameters
# http://www.ros.org/wiki/costmap_2d

### Coordinate frame and tf parameters ###
robot_base_frame:           base_link
transform_tolerance:        0.5

# ---Vector footprint (Meters):---
footprint: [[0.39,0.3],[0.39,-0.3],[-0.39,-0.3],[-0.39,0.3]]
#footprint: [[0.87,0.52],[0.87,-0.4],[-0.56,-0.4],[-0.56,0.52]]

### Costmap definitions ###
update_frequency: 8.0 # laserscans are 15 Hz. Be conservative
publish_frequency: 5.0 # publish freq is usually < update_freq
obstacle_layer/footprint_clearing_enabled: true

#raytrace_range must be less than max range of sensor.
observation_sources: base_scan_filtered
base_scan_filtered: {data_type: LaserScan, topic: movo/base_scan_filtered, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3.5, raytrace_range: 8.0}
