# TODO: Need to understand all EBandPlannerROS Params
# Not just those listed here
EBandPlannerROS:
  # Though the Movo is holonomic not diff drive,
  # This planner reports that holonomic support
  # is "experimental"
  differential_drive: true
  max_acceleration: 2.0
  max_vel_lin: 0.45
  max_vel_th: 0.5
  min_vel_lin: 0.0
  min_vel_th: 0.0
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.12 # this is about 7 deg

