joint_configurations: {
    home: {
        head: {
            names: ["pan_joint", "tilt_joint"],
            joints: [0.0, 0.0],
        },
        torso: {
            names: ["linear_joint"],
            joints: [0.1],
        },
        left_arm: {
            names: ["left_shoulder_pan_joint", "left_shoulder_lift_joint", "left_arm_half_joint", "left_elbow_joint", "left_wrist_spherical_1_joint", "left_wrist_spherical_2_joint", "left_wrist_3_joint"],
            joints: [1.4463922159520797, 1.596695035763699, 0.9848071437070933, 2.5494744715692814, -2.004909960289334, 1.8316609450514283, -2.8256088565680004],
        },
        right_arm: {
            names: ["right_shoulder_pan_joint", "right_shoulder_lift_joint", "right_arm_half_joint", "right_elbow_joint", "right_wrist_spherical_1_joint", "right_wrist_spherical_2_joint", "right_wrist_3_joint"],
            joints: [-1.189840720238987, -1.8304754388921793, -0.31277335632770153, -2.367960136151233, 0.9231204765356429, 1.534414350511106, 2.8363235525817165],
        }
    },
    handoff: {
        head: {
            names: ["pan_joint", "tilt_joint"],
            joints: [0.0, 0.0],
        },
        torso: {
            names: ["linear_joint"],
            joints: [0.4],
        },
        right_arm: {
            names: ["right_shoulder_pan_joint", "right_shoulder_lift_joint", "right_arm_half_joint", "right_elbow_joint", "right_wrist_spherical_1_joint", "right_wrist_spherical_2_joint", "right_wrist_3_joint"],
            joints: [-1.497173771091874, -0.05384432355144005, -0.0472769683033043, -1.4575817535881566, 3.1601009435928535, 1.2459021253979168, 1.515535734175753],
        }
    },
    open_gripper: {
        left_gripper: {
            names: ["left_gripper_finger1_joint", "left_gripper_finger2_joint", "left_gripper_finger3_joint"],
            joints: [0.23, 0.23, 0.23],
        },
        right_gripper: {
            names: ["right_gripper_finger1_joint", "right_gripper_finger2_joint", "right_gripper_finger3_joint" ]
            joints: [0.23, 0.23, 0.23],
        }
    },
    closed_gripper: {
        left_gripper: {
            names: ["left_gripper_finger1_joint", "left_gripper_finger2_joint", "left_gripper_finger3_joint"],
            joints: [0, 0, 0],
        },
        right_gripper: {
            names: ["right_gripper_finger1_joint", "right_gripper_finger2_joint", "right_gripper_finger3_joint" ]
            joints: [0, 0, 0],
        }
    },
}
