rooms: {
  room0: {
    door: {
      position: {
        x: 5.8,
        y: 1.8,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }
    },
    bed: {
      position: {
        x: 0.85,
        y: -0.95,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: -0.7071067811865475,
        w: -0.7071067811865475
      }
    }
  },
  home: {
    idle: {
      position: {
        x: 7.85,
        y: 6.5,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: -0.7071067811865475,
        w: -0.7071067811865475
      }   
    }
  }
}