rooms: {
  room0: {
    doorside: {
      position: {
        x: 6.0799,
        y: 1.0996,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: -0.9843978814671521,
        w: 0.1759568440356406
      }
    },
    bedside: {
      position: {
        x: 2.936,
        y: -1.87,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: -0.618584943250382,
        w: 0.7857179315657252
      }
    }
  },
  home: {
    default: {
      position: {
        x: -19.592247009277344,
        y: 15.489871978759766,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: -0.5510652550369382,
        w: 0.8344621529410872
      }   
    }
  },
  stock: {
    default: {
      position: {
        x: 10.35592269897461,
        y: -6.343851566314697,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0.17118407401895144,
        w: 0.985239063782123
      }   
    }
  },
}
