class ScreenConfig:
    CANCEL_BUTTON_FONT_SIZE = 40
    ESTOP_XPOS = 0.925
    ESTOP_YPOS = 0.9
    INCR_BUTTON_HEIGHT = 0.05
    INCR_BUTTON_WIDTH = 0.1
    INCR_BUTTON_XPOS = 0.75
    INCR_BUTTON_FONTSIZE = 50
