# body_part is one of {left_arm,right_arm,torso,head}
string configuration
int8 LEFT_ARM=0
int8 RIGHT_ARM=1
int8 LEFT_GRIPPER = 2
int8 RIGHT_GRIPPER = 3
int8 TORSO=4
int8 HEAD=5
int8 body_part
---
sensor_msgs/JointState jnt_state
