#
# http://www.ros.org/wiki/amcl
# The first commented value is the default per the wiki
# The second commented value is the default per nav/amcl/examples
# The third commented value is the defaults in amcl_node.cpp
#
# The map file is specified in launch/amcl.launch

odom_frame_id:    odom
base_frame_id:    base_link
global_frame_id:  map
  
# Overall filter parameters
min_particles:        350       #default 100 ,          last 100
max_particles:        5000      #default 5000 increased from Kinova value of 2000
kld_err:              0.01      #default 0.01,          last 0.05
kld_z:                0.99      #default 0.99,          last 0.95
update_min_d:         0.2       #default 0.2,           last 0.1
update_min_a:         0.5235    #default pi/6 (0.5235)  last 0.25
resample_interval:    1         #default 1              last 2
transform_tolerance:  0.5       #default 0.1            last 0,1, before 1.0
recovery_alpha_slow:  0.001     #default 0.0
recovery_alpha_fast:  0.1       #default 0.0
initial_pose_x:       0.0       #default 0.0
initial_pose_y:       0.0       #default 0.0
initial_pose_a:       0.0       #default 0.0
initial_cov_xx:       0.2       #default 0.25
initial_cov_yy:       0.2       #default 0.25
initial_cov_aa:       0.12      #default (pi/12)*(pi/12) (0.06853)
gui_publish_rate:     -1.0      #default -1.0
save_pose_rate:       0.5       #default 0.5
use_map_topic:        false     #default false
first_map_only:       false     #default false

# Laser Model Parameters 
laser_min_range:            0.05    #default -1.0
laser_max_range:            10.0    #default -1.0
laser_max_beams:            60     #default 30
laser_z_hit:                0.90   #default 0.95
laser_z_rand:               0.1   #default 0.05
laser_sigma_hit:            0.1   #default 0.2  
laser_lambda_short:         0.1   #default 0.1
laser_likelihood_max_dist:  3.0    #default 2.0
laser_model_type:           likelihood_field #default likelihood_field

# Odometery model parameters
# Corrected from Kinova config
# omni model-type had bug. use omni-corrected instead
odom_model_type:  omni-corrected
odom_alpha1:      0.005
odom_alpha2:      0.005
odom_alpha3:      0.010
odom_alpha4:      0.005
odom_alpha5:      0.003
