local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   static_map: false
   rolling_window: true
   width: 8.0
   height: 8.0
   resolution: 0.05
   inflation_radius: 0.45
   footprint_padding: 0.0
