rooms: {
  room0: {
    door: {
      position: {
        x: 0,
        y: 0,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }
    },
    bed: {
      position: {
        x: 0,
        y: 0,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }
    }
  },
  room1: {
    door: {
      position: {
        x: 0,
        y: 0,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }
    },
    bed: {
      position: {
        x: 0,
        y: 0,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }
    }
  },
  room2: {
    door: {
      position: {
        x: 0,
        y: 0,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }
    },
    bed: {
      position: {
        x: 0,
        y: 0,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }
    }
  },
  home: {
    idle: {
      position: {
        x: 0,
        y: 0,
        z: 0
      },
      orientation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1
      }   
    }
  }
}