name: ros_colcon_CI_nightingale
on: [push, pull_request]

env:
  PACKAGES_TO_TEST:
    nightingale_teleop
    

jobs:
  compile:
    name: ROS 1 CI Action
    runs-on: [ubuntu-20.04]

    container:
      image: ubuntu:focal
      options: -u root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.4.1
        with:
          required-ros-distributions: noetic

      - name: Run CI
        uses: ros-tooling/action-ros-ci@0.2.7
        with:
          target-ros1-distro: noetic
          package-name: ${{ env.PACKAGES_TO_TEST }}
          skip-tests: true
